name: Trickster OPERA
favicon: null
layout_spectrum: 0.47106406441889703
typography_spectrum: 0.7706508166156709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13001702236942947
  lightness: 0.7941121365875006
  saturation: 0.5871873784344643
  rhythmicContrast: 0.6420818674378097
purpose: []
